services:
  app:
    build: .
    container_name: django-template-app
    image: solnustec.com/django-template:latest
    restart: always
    env_file:
      - .env
    environment:
      - $(cat local.env 2>/dev/null | xargs)  # Carga local.env si existe
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8000"
    volumes:
      - ./:/src
